import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb } from '../packages/daemon/src/db/index.js';
import { buildServer } from '../packages/daemon/src/api/server.js';
import { Scheduler } from '../packages/daemon/src/ingest/scheduler.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const runtimeRoot = process.env.QUOTAPULSE_REVIEW_ROOT ? resolve(process.env.QUOTAPULSE_REVIEW_ROOT) : root;
const bundled = runtimeRoot !== root;
const electron = createRequire(resolve(runtimeRoot, 'package.json'))('electron');
if (bundled) assert.ok(electron.startsWith(runtimeRoot + '\\'));
const output = resolve(root, 'screens/unresponsive-recovery', bundled ? 'bundle' : 'source');
const profiles = resolve(root, 'tmp/unresponsive-recovery');
mkdirSync(output, { recursive: true }); mkdirSync(profiles, { recursive: true });
const report = resolve(output, 'verification.json'); rmSync(report, { force: true });
const data = mkdtempSync(resolve(profiles, 'instance-'));
writeFileSync(resolve(data, 'pet-settings.json'), JSON.stringify({ schemaVersion: 4, enabled: false }));
const db = openDb(':memory:');
db.exec("INSERT INTO app_setting(id,pet_enabled,tray_animation_enabled,hidden_subscriptions,updated_at) VALUES(1,0,0,'[]',0)");
const daemon = buildServer(db, new Scheduler(db, [], { pollMs: 1000000, detectMs: 1000000 }), { token: 'synthetic-hang-test', port: 7813, webRoot: resolve(runtimeRoot, 'packages/web/dist') });
try {
  await daemon.listen({ host: '127.0.0.1', port: 7813 });
  writeFileSync(resolve(data, 'daemon.lock'), JSON.stringify({ pid: process.pid, port: 7813, token: 'synthetic-hang-test', startedAt: Date.now() }));
  const child = spawn(electron, [resolve(root, 'scripts/unresponsive-probe.cjs')], { windowsHide: true, stdio: 'ignore', env: { ...process.env, ELECTRON_RUN_AS_NODE: undefined, QUOTAPULSE_TEST_RUNTIME_ROOT: runtimeRoot, QUOTAPULSE_TEST_REPORT: report, QUOTAPULSE_DATA_DIR: data, QUOTAPULSE_PORT: '7813', QUOTAPULSE_NODE_EXE: process.execPath, QUOTAPULSE_READERS: 'off' } });
  const code = await new Promise<number | null>((resolve, reject) => { child.once('error', reject); child.once('exit', resolve); });
  const result = JSON.parse(readFileSync(report, 'utf8'));
  writeFileSync(report, JSON.stringify({ ...result, runtimeRoot, bundled, database: 'synthetic in-memory; no adapters', limitations: ['dashboard actual hang only; other surfaces remain separate', 'native input generated by test; no physical clicks'] }, null, 2));
  assert.equal(code, 0, JSON.stringify(result)); assert.equal(result.status, 'passed');
  console.log('Actual dashboard unresponsive recovery passed.');
} finally { await daemon.close(); db.close(); }
